### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by psychomad** [philarkwright/DGA-Detection#1]
Hi
I try to install using first 
pip install -r requirements.txt
and then 
pip3 install -r requirements.txt

because first way didn't work
both way show me

Collecting scapy
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xe7ucgvg/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token

But i have scapy already update and working

Any clue?

**Comment by philarkwright** [comment]
The script was written for python 2.7 so wouldn't work with python 3. Which linux distro are you using? Try **sudo apt-get install scapy**. Then try installing the rest and run using **sudo python2.7 dga_detection.py**
